---
version: "3.7"
services:
  app:
    build: .
    command: bundle exec rails server --binding 0.0.0.0
    depends_on:
      - db
      - redis
    environment:
      BUNDLE_PATH: /usr/local/bundle
      DB_HOST: db
      REDIS_URL: redis://redis
    ports:
      - "3000:3000"
    volumes:
      - bundle:/usr/local/bundle
      - .:/home/rtg

  worker:
    image: ruby-the-gryphon_app
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    environment:
      BUNDLE_PATH: /usr/local/bundle
      DB_HOST: db
      REDIS_URL: redis://redis
    volumes:
      - bundle:/usr/local/bundle
      - .:/home/rtg

  test:
    image: ruby-the-gryphon_app
    command: bundle exec rspec
    depends_on:
      - db
      - redis
      - chromedriver
    environment:
      BASE_URL: http://test:3000
      BUNDLE_PATH: /usr/local/bundle
      DB_HOST: db
      REDIS_URL: redis://redis
    volumes:
      - bundle:/usr/local/bundle
      - .:/home/rtg

  db:
    image: postgres:10.2
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:4
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  chromedriver:
    image: 'robcherry/docker-chromedriver'
    restart: on-failure
    shm_size: 1G
    environment:
      - CHROMEDRIVER_WHITELISTED_IPS=""
    ports:
      - target: 4444
        published: 4444
    networks:
      default:
        aliases:
          - chromedriver
   
volumes:
  bundle:
  db:
  redis:
